In [1]:
import torch
import pandas as pd

In [2]:
from pysentimiento.preprocessing import preprocess_tweet

In [3]:
pwd

'/home/darkstar/Workspace/ai/nlp/peruvian-slang-sentiment'

In [4]:
pd.set_option("max_colwidth", 300)

In [5]:
df = pd.read_csv(r'text-extraction/[labeling]dataset-01-sorted.csv')
df

,id_slang,slang,sentence,label,char_count,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,75,anda,Anda,0,4,NaN,NaN,NaN,NaN
1,2139,cagón,cagón,0,5,NaN,NaN,NaN,NaN
2,1392,pesado,pesado,0,6,NaN,NaN,NaN,NaN
3,275,carajo,carajo,0,6,NaN,NaN,NaN,NaN
4,184,cabrón,Cabrón,0,6,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
21389,41,achorado,"y los tres chiflados siguen cantando a voz en cuello y en inglés y con toda la concha del mundo, y yo ahí sentadito y timidísimo escuchándolos embobado y mirándole de reojo el pechito de gaviota al loco mariano, y los dos ex convictos de la otra mesa siguen mirándonos feo y yo presiento que esto...",0,3568,NaN,NaN,NaN,NaN
21390,548,concha,"y los tres chiflados siguen cantando a voz en cuello y en inglés y con toda la concha del mundo, y yo ahí sentadito y timidísimo escuchándolos embobado y mirándole de reojo el pechito de gaviota al loco mariano, y los dos ex convictos de la otra mesa siguen mirándonos feo y yo presiento que esto...",0,3568,NaN,NaN,NaN,NaN
21391,1065,macha,"y los tres chiflados siguen cantando a voz en cuello y en inglés y con toda la concha del mundo, y yo ahí sentadito y timidísimo escuchándolos embobado y mirándole de reojo el pechito de gaviota al loco mariano, y los dos ex convictos de la otra mesa siguen mirándonos feo y yo presiento que esto...",0,3568,NaN,NaN,NaN,NaN
21392,2161,cojudo,"y los tres chiflados siguen cantando a voz en cuello y en inglés y con toda la concha del mundo, y yo ahí sentadito y timidísimo escuchándolos embobado y mirándole de reojo el pechito de gaviota al loco mariano, y los dos ex convictos de la otra mesa siguen mirándonos feo y yo presiento que esto...",0,3568,NaN,NaN,NaN,NaN
21393,275,carajo,"y los tres chiflados siguen cantando a voz en cuello y en inglés y con toda la concha del mundo, y yo ahí sentadito y timidísimo escuchándolos embobado y mirándole de reojo el pechito de gaviota al loco mariano, y los dos ex convictos de la otra mesa siguen mirándonos feo y yo presiento que esto...",0,3568,NaN,NaN,NaN,NaN

In [6]:
df = df[df.label.isin(["1","2","3"])]
#new_df = new_df.loc[:, ['id_slang','slang', 'sentence', 'label']]
df = df.loc[:, ['sentence', 'label']]
df = df.rename(columns={"sentence":"text"})
df = df.reset_index(drop=True)
df = df.astype({'label':'int'})
df

                                     text  label
0                               Oe Chacal      2
1                               Anda vete      3
2                              a la firme      2
3                              Chau, cojo      3
4                             Tengo plata      2
..                                    ...    ...
407  Ahorita la chola te trae tu desayuno      1
408  Siempre he sacado buenas notas, papá      1
409  Hoy reventamos a esos conchasumadres      3
410  Un día me cae un piedrón y la cagada      3
411  Ese chico es un drogadicto asqueroso      3

[412 rows x 2 columns]

In [7]:
# label encode
def label_encode(x):
    if x == 1:#positive
        return 2
    if x == 2:#neutral
        return 1
    if x == 3:#negative
        return 0

In [8]:
df["label"] = df["label"].apply(lambda x: label_encode(x))

In [9]:
df.sample(n = 30)

                                     text  label
254            Sus viejos son una ladilla      0
196                -Te ha dejado plantado      0
157                  te pusiste loco, men      0
111                    Ya le dije enantes      1
410  Un día me cae un piedrón y la cagada      0
217               EL CHACAL:  Está jodido      0
316        Se sonó la nariz con su chompa      0
170                 Se besaron suavemente      2
225               Esta noche cinco polvos      2
262           —¿Qué? Habla fuerte, carajo      0
220               No me chupo con mayores      1
87                      no seas malcriado      0
345       Te vio y casi se traga el pucho      0
185                Movía mi pelota, flaco      2
398   Que se joda la vieja por imprudente      0
215               Pronto estaremos viejos      0
119                    Son unos rosquetes      0
23                          Dale U carajo      2
239             Pero allá tú, es tu plata      0
212               No le gustan los negros      0
298         Ese fue el momento más jodido      0
127                   Su viejo caga plata      2
130                   “Llora, llora cagón      0
177                Solo te gusta cacharme      0
310         —Muere, cabro apestoso —gritó      0
380    Pero yo qué pito toco en todo esto      0
141                  —Ay, pobre, qué piña      0
318        no pasa nada, todos tranquilos      2
238              suave que te desintegras      0
307         cuando venga lo voy a cuadrar      0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 412 entries, 0 to 411
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    412 non-null    object
 1   label   412 non-null    int64
dtypes: int64(1), object(1)
memory usage: 6.6+ KB

In [11]:
#split train test
from sklearn.model_selection import train_test_split


random_state=1
train_df_, val_df = train_test_split(df, 
                                    test_size=0.10, 
                                    random_state=random_state, 
                            stratify=df.label.values)

In [12]:

train_df, test_df = train_test_split(train_df_, 
                                    test_size=0.10, 
                                    random_state=42, 
                            stratify=train_df_.label.values)

In [13]:
train_df.to_csv('pilot-test/train.csv', index=False)

In [14]:
val_df.to_csv('pilot-test/val.csv', index=False)

In [15]:
test_df.to_csv('pilot-test/test.csv', index=False)

In [16]:
!ls -l ./pilot-test/

total 52
-rw-r--r-- 1 darkstar darkstar    89 Oct  4 23:40 main.py
-rw-rw-r-- 1 darkstar darkstar 22756 Oct  5 03:04 pilot-train.ipynb
-rw-rw-r-- 1 darkstar darkstar   956 Oct  5 03:06 test.csv
drwxrwxr-x 2 darkstar darkstar  4096 Oct  5 02:55 test_trainer
-rw-rw-r-- 1 darkstar darkstar  9390 Oct  5 03:06 train.csv
-rw-rw-r-- 1 darkstar darkstar  1180 Oct  5 03:06 val.csv

In [17]:
len(train_df)

333

In [18]:
len(val_df)

42

In [19]:
len(test_df)

37

In [20]:
len(df)

412