In [1]:
import sys
import pandas as pd 
import os 
import glob

In [2]:
MIN_CHAR_LENGHT = 20

In [3]:
csv_files = glob.glob(os.path.join(r"facebook/extraction-3/", "*.csv"))

In [4]:
#csv_files

In [5]:
df_list = (pd.read_csv(file, sep = ';') for file in csv_files)

In [6]:
big_df = pd.concat(df_list, ignore_index=True)

C:\Users\JairL\AppData\Local\Temp\ipykernel_19084\1999715855.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = (pd.read_csv(file, sep = ';') for file in csv_files)
C:\Users\JairL\AppData\Local\Temp\ipykernel_19084\1999715855.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = (pd.read_csv(file, sep = ';') for file in csv_files)
C:\Users\JairL\AppData\Local\Temp\ipykernel_19084\1999715855.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = (pd.read_csv(file, sep = ';') for file in csv_files)
C:\Users\JairL\AppData\Local\Temp\ipykernel_19084\1999715855.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = (pd.read_csv(file, sep = ';') for file in csv_files)
C:\Users\JairL\AppData\Local\Temp\ipykernel_19084\1999715855.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = (pd.read_csv(file, sep = ';') for file in csv_files)
C:\Users\JairL\AppData\Local\Temp\ipykernel_19084\1999715855.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = (pd.read_csv(file, sep = ';') for file in csv_files)
C:\Users\JairL\AppData\Local\Temp\ipykernel_19084\1999715855.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = (pd.read_csv(file, sep = ';') for file in csv_files)
C:\Users\JairL\AppData\Local\Temp\ipykernel_19084\1999715855.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = (pd.read_csv(file, sep = ';') for file in csv_files)
C:\Users\JairL\AppData\Local\Temp\ipykernel_19084\1999715855.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = (pd.read_csv(file, sep = ';') for file in csv_files)
C:\Users\JairL\AppData\Local\Temp\ipykernel_19084\1999715855.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = (pd.read_csv(file, sep = ';') for file in csv_files)
C:\Users\JairL\AppData\Local\Temp\ipykernel_19084\1999715855.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = (pd.read_csv(file, sep = ';') for file in csv_files)

In [7]:
df = big_df.dropna(subset=['message'])

In [8]:
df = df[df['message'].str.len()>=MIN_CHAR_LENGHT]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2021181 entries, 6 to 3364645
Data columns (total 12 columns):
 #   Column        Dtype
---  ------        -----
 0   level         object
 1   id            object
 2   parent_id     object
 3   object_id     object
 4   object_type   object
 5   object_key    object
 6   query_status  object
 7   query_time    object
 8   query_type    object
 9   name          object
 10  message       object
 11  path          float64
dtypes: float64(1), object(11)
memory usage: 200.5+ MB

In [10]:
df = df.drop_duplicates(subset=['message'], keep='first')

In [11]:
df

,level,id,parent_id,object_id,object_type,object_key,query_status,query_time,query_type,name,message,path
6,1,14,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Las hijas de kingteka tienen buena coreo. GA,NaN
7,1,15,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,estas en pasta causa,NaN
8,1,16,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Puedo ver este video un millón de veces y no m...,NaN
10,1,18,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Valerie Nj que fue con tu show? tas facturand...,NaN
14,1,22,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Dicen que se vió esos pasitos Skeres en el ton...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3364603,1,18507,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:10.746875,Facebook:/<comment-id>/comments,NaN,Holaaaaa ❤️❤️❤️❤️❤️❤️,NaN
3364605,1,18509,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:10.746875,Facebook:/<comment-id>/comments,NaN,Edith Ana Quispe mira esto,NaN
3364628,1,18532,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:11.059672,Facebook:/<comment-id>/comments,NaN,Holaa yifda un saludito,NaN
3364633,1,18537,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:11.059672,Facebook:/<comment-id>/comments,NaN,Holiii.. Yo quiero tu libro 😍,NaN
3364645,1,18549,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:11.059672,Facebook:/<comment-id>/comments,NaN,Yidda me recomiendas al neurópediatra para la ...,NaN

In [12]:
#exclude words
words = ['jaja','jajaja', 'jajajajajajja', 'jajajajajajaja','jajajajjajajajaja','Jajajajajajajajaja','jajajaja','jajajajjajajajaja', 'jajajajja','jijiji', 'saludo', 'saluda', 'xd', 'hola', 'zzz']
def remove_words(text):
    for x in words:
        text = text.lower().replace(x, '')
    if len(text)>=MIN_CHAR_LENGHT:
        return True
    return False

In [13]:
print(remove_words('Belén Sánchez Castillo jajajajaja'))

True

In [14]:
df

,level,id,parent_id,object_id,object_type,object_key,query_status,query_time,query_type,name,message,path
6,1,14,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Las hijas de kingteka tienen buena coreo. GA,NaN
7,1,15,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,estas en pasta causa,NaN
8,1,16,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Puedo ver este video un millón de veces y no m...,NaN
10,1,18,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Valerie Nj que fue con tu show? tas facturand...,NaN
14,1,22,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Dicen que se vió esos pasitos Skeres en el ton...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3364603,1,18507,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:10.746875,Facebook:/<comment-id>/comments,NaN,Holaaaaa ❤️❤️❤️❤️❤️❤️,NaN
3364605,1,18509,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:10.746875,Facebook:/<comment-id>/comments,NaN,Edith Ana Quispe mira esto,NaN
3364628,1,18532,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:11.059672,Facebook:/<comment-id>/comments,NaN,Holaa yifda un saludito,NaN
3364633,1,18537,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:11.059672,Facebook:/<comment-id>/comments,NaN,Holiii.. Yo quiero tu libro 😍,NaN
3364645,1,18549,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:11.059672,Facebook:/<comment-id>/comments,NaN,Yidda me recomiendas al neurópediatra para la ...,NaN

In [15]:
#remove rows that are too small when excluding the list.
df['valid'] = df['message'].apply(lambda row: remove_words(row))
df

,level,id,parent_id,object_id,object_type,object_key,query_status,query_time,query_type,name,message,path,valid
6,1,14,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Las hijas de kingteka tienen buena coreo. GA,NaN,True
7,1,15,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,estas en pasta causa,NaN,True
8,1,16,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Puedo ver este video un millón de veces y no m...,NaN,True
10,1,18,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Valerie Nj que fue con tu show? tas facturand...,NaN,True
14,1,22,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Dicen que se vió esos pasitos Skeres en el ton...,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3364603,1,18507,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:10.746875,Facebook:/<comment-id>/comments,NaN,Holaaaaa ❤️❤️❤️❤️❤️❤️,NaN,False
3364605,1,18509,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:10.746875,Facebook:/<comment-id>/comments,NaN,Edith Ana Quispe mira esto,NaN,True
3364628,1,18532,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:11.059672,Facebook:/<comment-id>/comments,NaN,Holaa yifda un saludito,NaN,False
3364633,1,18537,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:11.059672,Facebook:/<comment-id>/comments,NaN,Holiii.. Yo quiero tu libro 😍,NaN,True
3364645,1,18549,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:11.059672,Facebook:/<comment-id>/comments,NaN,Yidda me recomiendas al neurópediatra para la ...,NaN,True

In [16]:
df_false = df[df['valid']== False]
df_false

,level,id,parent_id,object_id,object_type,object_key,query_status,query_time,query_type,name,message,path,valid
106,1,114,3,3963455660362592,data,data.*,fetched (200),2023-10-03 20:29:35.809339,Facebook:/<comment-id>/comments,NaN,Viktor VanDort jajaja 😂,NaN,False
339,1,349,7,372233297036050,data,data.*,fetched (200),2023-10-03 20:30:15.129249,Facebook:/<comment-id>/comments,NaN,Saludame paaaaapiiiiii,NaN,False
355,1,365,7,372233297036050,data,data.*,fetched (200),2023-10-03 20:30:15.537832,Facebook:/<comment-id>/comments,NaN,Hola chavosorrrrr!!!!,NaN,False
444,1,454,7,372233297036050,data,data.*,fetched (200),2023-10-03 20:30:16.787158,Facebook:/<comment-id>/comments,NaN,Saludame porfa chavito,NaN,False
465,1,475,7,372233297036050,data,data.*,fetched (200),2023-10-03 20:30:17.108271,Facebook:/<comment-id>/comments,NaN,chavito me saludas c:,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3364553,1,18457,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:09.931131,Facebook:/<comment-id>/comments,NaN,Saludos desde Pisco ☺,NaN,False
3364555,1,18459,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:09.931131,Facebook:/<comment-id>/comments,NaN,Hola . Saludos de Arequipa,NaN,False
3364593,1,18497,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:10.746875,Facebook:/<comment-id>/comments,NaN,Hola comadre 😄 👑✨💐👋😘,NaN,False
3364603,1,18507,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:10.746875,Facebook:/<comment-id>/comments,NaN,Holaaaaa ❤️❤️❤️❤️❤️❤️,NaN,False
3364628,1,18532,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:11.059672,Facebook:/<comment-id>/comments,NaN,Holaa yifda un saludito,NaN,False

In [17]:
df =df[df['valid']== True]

In [18]:
df

,level,id,parent_id,object_id,object_type,object_key,query_status,query_time,query_type,name,message,path,valid
6,1,14,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Las hijas de kingteka tienen buena coreo. GA,NaN,True
7,1,15,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,estas en pasta causa,NaN,True
8,1,16,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Puedo ver este video un millón de veces y no m...,NaN,True
10,1,18,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Valerie Nj que fue con tu show? tas facturand...,NaN,True
14,1,22,2,630750614924803,data,data.*,fetched (200),2023-10-03 20:29:29.755992,Facebook:/<comment-id>/comments,NaN,Dicen que se vió esos pasitos Skeres en el ton...,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3364594,1,18498,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:10.746875,Facebook:/<comment-id>/comments,NaN,Hola toda me podrías mandar saludos soy Yarexs...,NaN,True
3364598,1,18502,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:10.746875,Facebook:/<comment-id>/comments,NaN,Desde Argentina un beso te mando,NaN,True
3364605,1,18509,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:10.746875,Facebook:/<comment-id>/comments,NaN,Edith Ana Quispe mira esto,NaN,True
3364633,1,18537,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:11.059672,Facebook:/<comment-id>/comments,NaN,Holiii.. Yo quiero tu libro 😍,NaN,True
3364645,1,18549,3,580243363258960,data,data.*,fetched (200),2023-10-10 22:24:11.059672,Facebook:/<comment-id>/comments,NaN,Yidda me recomiendas al neurópediatra para la ...,NaN,True

In [19]:
df = df.reset_index()

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1900676 entries, 0 to 1900675
Data columns (total 14 columns):
 #   Column        Dtype
---  ------        -----
 0   index         int64
 1   level         object
 2   id            object
 3   parent_id     object
 4   object_id     object
 5   object_type   object
 6   object_key    object
 7   query_status  object
 8   query_time    object
 9   query_type    object
 10  name          object
 11  message       object
 12  path          float64
 13  valid         bool
dtypes: bool(1), float64(1), int64(1), object(11)
memory usage: 190.3+ MB

In [21]:
df.sample(30)

,index,level,id,parent_id,object_id,object_type,object_key,query_status,query_time,query_type,name,message,path,valid
309552,455866,1,7992,1,1120152398107908,data,data.*,fetched (200),2023-10-15 11:05:05.422941,Facebook:/<comment-id>/comments,NaN,Franco Saravia Mira webon!,NaN,True
1484989,2660176,1,12556,83,341143191221277,data,data.*,fetched (200),2023-10-18 08:31:41.850894,Facebook:/<comment-id>/comments,NaN,"Le hubieras colocado de fondo el tema: "" fly m...",NaN,True
18244,36856,1,23109,251,820798069643272,data,data.*,fetched (200),2023-10-26 17:21:57.819776,Facebook:/<comment-id>/comments,NaN,Es como debe de ser siempre pa adelante sufrir...,NaN,True
881416,1329571,1,15700,56,668688510547070,data,data.*,fetched (200),2023-10-17 19:22:26.966340,Facebook:/<comment-id>/comments,NaN,para mi que es perro por qur ahi esta ladrando...,NaN,True
1138298,1763917,1,52127,207,924931551942550,data,data.*,fetched (200),2023-10-23 21:23:41.051882,Facebook:/<comment-id>/comments,NaN,Cinthia Gonzales Inuma me parece a alguien est...,NaN,True
671181,1029236,1,157705,44,1169040173828016,data,data.*,fetched (200),2023-10-25 21:00:44.611702,Facebook:/<comment-id>/comments,NaN,Tontos los asia o se asian en gobiernos anteri...,NaN,True
1219999,1889157,1,220,12,10155214397801186,data,data.*,fetched (200),2023-10-08 17:23:26.194956,Facebook:/<comment-id>/comments,NaN,Sorteo de entradas zona vip ?,NaN,True
798810,1205632,1,19796,43,648183440552695,data,data.*,fetched (200),2023-10-08 21:45:14.158134,Facebook:/<comment-id>/comments,NaN,QUE OPINAN.....DE POCHO ROSPIGLIOSI???,NaN,True
767969,1154016,1,36329,198,388059208515084,data,data.*,fetched (200),2023-10-22 11:59:23.040553,Facebook:/<comment-id>/comments,NaN,Angela Carrasco se ha de estar vomitando con l...,NaN,True
769756,1156894,1,39207,215,500899860728789,data,data.*,fetched (200),2023-10-22 12:00:28.491963,Facebook:/<comment-id>/comments,NaN,La mejor cancion que canto maira goñi hermosa ...,NaN,True
1813177,3223092,1,15415,62,1564098203684783,data,data.*,fetched (200),2023-10-09 20:24:39.526541,Facebook:/<comment-id>/comments,NaN,Cesibel Trujillo xdddddddd,NaN,True
1337435,2100685,1,159530,552,678008835647113,data,data.*,fetched (200),2023-10-15 09:09:05.868611,Facebook:/<comment-id>/comments,NaN,Purita naturaleza :3,NaN,True
736005,1106486,1,234955,60,787266132427161,data,data.*,fetched (200),2023-10-25 21:46:05.256721,Facebook:/<comment-id>/comments,NaN,Que Cáncer no hay Nada de Pruebas Osico de T...,NaN,True
314630,464036,1,16162,1,1120152398107908,data,data.*,fetched (200),2023-10-15 11:08:36.006192,Facebook:/<comment-id>/comments,NaN,Diego Hurtado Gabriela Zela Paredes,NaN,True
266943,391207,1,269788,325,219431976046544,data,data.*,fetched (200),2023-10-25 08:46:07.465503,Facebook:/<comment-id>/comments,NaN,PRIORICEMOS... ellos ahora no lo son.,NaN,True
1518722,2728292,1,21321,56,206977183918573,data,data.*,fetched (200),2023-10-08 17:01:12.959706,Facebook:/<comment-id>/comments,NaN,"Excelente Naty, eres la mejor y gracias x los ...",NaN,True
1250660,1945229,1,4074,13,311260028131677,data,data.*,fetched (200),2023-10-15 08:22:05.794953,Facebook:/<comment-id>/comments,NaN,"Gracias por tu visita Manolo, nos ayudas de so...",NaN,True
1403499,2214272,1,9783,60,841383946796535,data,data.*,fetched (200),2023-10-13 16:19:50.747825,Facebook:/<comment-id>/comments,NaN,Ya quiero estar así APerez Perez,NaN,True
1546437,2776871,1,8203,5743,900999303984821,data,data.*,fetched (200),2023-10-08 08:16:14.335128,Facebook:/<comment-id>/comments,NaN,Duelvanle el cupo como van a ser teerible atr...,NaN,True
236716,353388,1,231969,281,327214538460450,data,data.*,fetched (200),2023-10-24 21:19:51.174320,Facebook:/<comment-id>/comments,NaN,"Ese video le falta mas sentimiento, deberia se...",NaN,True
1219982,1889133,1,196,12,10155214397801186,data,data.*,fetched (200),2023-10-08 17:23:25.581866,Facebook:/<comment-id>/comments,NaN,Apla gato mañana en la costa verde,NaN,True
1215589,1879354,1,22191,1,1693898353972863,data,data.*,fetched (200),2023-09-28 22:47:31.737393,Facebook:/<post-id>/comments,NaN,Luis Fernando Quintero,NaN,True
461714,747216,1,89,1,787924516326565,data,data.*,fetched (200),2023-10-08 11:39:37.572970,Facebook:/<comment-id>/comments,NaN,Que decepción cueva. Tantos hinchas de con am...,NaN,True
1533212,2758145,1,15234,158,707884626082607,data,data.*,fetched (200),2023-10-12 01:12:50.684596,Facebook:/<comment-id>/comments,NaN,jajajjaja noooooo horror mi esposo deja la rop...,NaN,True
1476617,2645833,1,38105,41,865690016940847,data,data.*,fetched (200),2023-10-11 22:18:44.343910,Facebook:/<comment-id>/comments,NaN,"Besos de Joaquín, le enviaré a tu mami el vide...",NaN,True
1373292,2162144,1,4110,1,5205319746238657,data,data.*,fetched (200),2023-10-10 20:49:43.925863,Facebook:/<comment-id>/comments,NaN,"Divina una diosa te queda estupendo,seguí usán...",NaN,True
1032392,1583453,1,16922,73,961531144765968,data,data.*,fetched (200),2023-10-25 17:44:14.747261,Facebook:/<comment-id>/comments,NaN,Creo que me iré a Japón :v,NaN,True
909939,1370843,1,984,3,676414241115613,data,data.*,fetched (200),2023-10-22 19:28:23.595718,Facebook:/<comment-id>/comments,NaN,P Ces AV jajaja el futuro predisente,NaN,True
516805,834495,1,4626,2,1316886392292124,data,data.*,fetched (200),2023-10-26 19:41:27.557671,Facebook:/<comment-id>/comments,NaN,Desde Tangamandapio 🇷🇪🇷🇪🇷🇪🇷🇪,NaN,True
338897,510423,1,970,1,1157451784658852,data,data.*,fetched (200),2023-09-25 20:45:22.314789,Facebook:/<post-id>/comments,NaN,"Diga quién no ha tenido un amigo, hermano o pr...",NaN,True

In [22]:
#Slang Extraction

In [23]:
SENTENCE_LENGTH = 10000000 #limit of characters to extract
def extract_sentence(corpus, text):
    sentences = []
    for line in list(corpus):
        if (" "+text in line.lower()) & (len(line) <= SENTENCE_LENGTH):
#             print(line)
            sentences.append(line.strip().replace("\n"," "))
#             print('=============================================================================')
        
#     print(sentences)
    return sentences

In [24]:
df_slang = pd.read_csv(r'peruvian-slang.v1.csv', usecols = ['Jerga','tipo'])
df_slang

                          Jerga       tipo
0                            Pe      Jerga
1                            Oe      Jerga
2                       Lechero      Jerga
3                       Lenteja      Jerga
4               Tirarse la pera  expresión
...                         ...        ...
2339      Meter floro o florear  expresión
2340  Tus perras están ladrando  expresión
2341          Hacer una chancha  expresión
2342                Pitri mitri  expresión
2343        en la luna de paita  expresión

[2344 rows x 2 columns]

In [25]:
data = []
slang_length = 3 #minimun length of characters of an slang

In [26]:
pd.set_option("max_colwidth", 300)

In [27]:
df_sample = df.sample(10_000)
df_sample = df_sample[['id', 'object_id', 'message']]
df_sample

,id,object_id,message
705632,199617,731285401274716,Que irespomsabilidad e ignorancia de los padres...es.lamentable lo que les toca vivir a esos niños...la mujer es quien decide cuántos hijos quiere y puede tener y mantener...debio ir a planificación familiar desde.su primer embarazo ...que indignante...
1264614,31533,552751663470615,"Excelente!!!! Peruanidad pura en las alturas , cevichito y pisco sour, son mis favoritos ¡¡¡¡¡SALUD hasta el Huascaran!!!"
290973,27967,1456943327762145,Pamela Zamudio Ticona Juana Ticona Mendoza De Zamudio vamos?
784341,19425,2866144616739452,Jesus Alberto Diaz Carranza no eres tú???? Jajajaja nosotros celebramos los 15 😅😂
206898,190851,241252184119072,Betito habla de tu tia keiko ps ya deja el taper .
...,...,...,...
725433,222414,787266132427161,Manda preso a ese periodistas grosero
1508520,3015,1261113281024200,Regia Fumanchulovers 🥰
979560,110842,1120037765442191,Diana Lopez Velasquez así me vas a revisar?
533018,32877,1292007658374613,Esa magia ya no lo volveremos a ver en las canchas de fútbol era un deleite y se disfrutaba verlo jugar. El verdadero rey del fútbol
1748981,106859,884238275099746,Lindo tu programa y linda tu sonrisa

In [28]:
def find_slang(text):
    slangs = ""
    for i in df_slang.index:
        slang = df_slang['Jerga'][i].lower()
        if (len(slang)>slang_length):
            if " "+slang in text.lower():
                slangs += slang + ","
    return slangs

In [29]:
import psutil 
print('Physical Cores=', psutil.cpu_count(logical=False))
print('Logical Cores=',  psutil.cpu_count(logical=True))

Physical Cores= 8
Logical Cores= 16

In [30]:
#to run in multple cores
#pip install swifter

In [31]:
import swifter

In [32]:
import pandas as pd

# this is an example of common operations you have to perform on text
# data to go from raw text to clean text you can use for modelling
def process_df_function(df):
    output_df = df.copy()
    # replace weird double quotes with normal ones
    output_df['slangs'] = output_df['message'].swifter.apply(lambda row: find_slang(row))
    return output_df

In [33]:
import multiprocessing
import numpy as np

NUM_CORES = 5

# split the raw dataframe into chunks
df_chunks = np.array_split(df_sample ,NUM_CORES)

In [34]:
#df_chunks

In [35]:
# use a pool to spawn multiple proecsses
# with multiprocessing.Pool(NUM_CORES) as pool:
#     processed_df = pd.concat(pool.map(process_df_function, df_chunks), ignore_index=True)

In [36]:
df_sample['slangs'] = df_sample['message'].swifter.apply(lambda row: find_slang(row))
df_sample

Pandas Apply:   0%|          | 0/10000 [00:00<?, ?it/s]

,id,object_id,message,slangs
705632,199617,731285401274716,Que irespomsabilidad e ignorancia de los padres...es.lamentable lo que les toca vivir a esos niños...la mujer es quien decide cuántos hijos quiere y puede tener y mantener...debio ir a planificación familiar desde.su primer embarazo ...que indignante...,
1264614,31533,552751663470615,"Excelente!!!! Peruanidad pura en las alturas , cevichito y pisco sour, son mis favoritos ¡¡¡¡¡SALUD hasta el Huascaran!!!","pisco sour,pisco,huasca,"
290973,27967,1456943327762145,Pamela Zamudio Ticona Juana Ticona Mendoza De Zamudio vamos?,
784341,19425,2866144616739452,Jesus Alberto Diaz Carranza no eres tú???? Jajajaja nosotros celebramos los 15 😅😂,
206898,190851,241252184119072,Betito habla de tu tia keiko ps ya deja el taper .,"habla,"
...,...,...,...,...
725433,222414,787266132427161,Manda preso a ese periodistas grosero,
1508520,3015,1261113281024200,Regia Fumanchulovers 🥰,
979560,110842,1120037765442191,Diana Lopez Velasquez así me vas a revisar?,
533018,32877,1292007658374613,Esa magia ya no lo volveremos a ver en las canchas de fútbol era un deleite y se disfrutaba verlo jugar. El verdadero rey del fútbol,"cancha,"
1748981,106859,884238275099746,Lindo tu programa y linda tu sonrisa,

In [45]:
df_sample.sample(30)

,id,object_id,message,slangs
1684043,8833,576492860045118,Karoley Del Carpio Alegria,
61716,3008,1981665391906054,Maria Angela Heredia tú!,
740264,239874,1055309035100251,"La estrategia , me parece, esdisolver el congreso ,por la vía legal , Pero, ante una organización criminal del congreso y medios, me refiero a un sector, no todos, se necesita articular, en el campo de cultura, buscar espacios perdidos en la tv y si no imponer la ley de comunicaciones, domest...",
1368720,27668,1198368687625709,Si pero con su 1.37 mt. es más difícil.,
1707271,44060,455227608691568,Asu Hija! Mary Laura Barba,
227572,218980,630634820937108,Ay que ir Elizabeth Sánchez :(,
813187,39393,202350455936128,Roberto Carlos Leveroni Ochoa el candidato es el tío FOSATTI,
685458,175302,481427117079561,esa tu eres jente de kieko jojimore nu sabes Lu q estas ablando,
755864,15851,391880471730632,"Felicitaciones por Amy, lo que si no entiendo , que pito tocaba melisa loza como jurado y llevar a su hija ethel solo para promocionar su programa de la mañana?","pito,"
77713,19547,1379742119137580,Escuchen congresistas,
24993,1128,3494393237263522,Pvp por diamantes pongo la sala,
1138529,52499,795031585441288,No me pareció bien ...es mi opinión,
460100,10526,541216403583593,"mo tengan miedo en decir que Paolo no está para titular, está bien que sea el capitán, pero se tiene que ser realista!",
267817,270894,237514360699586,Pero han dicho que no a sido un motín solo que el jefe del penal recibió un disparo por medio de uno de los seguridad,
292962,31116,1427006427422502,Melanie Mayra Delgado Menendez,
1525614,35631,340368483576059,Saludos desde cajamarca Perú,
1216551,24603,1693898353972863,Luis Eduardo Aguirre Perdomo,"aguirre,"
129640,91093,494066311785000,"Hágalo compañero, o que te enseñan en la universidad 😎😎🤣🏄🏄🏄",
104310,57134,1816979338502168,Te acuerdas cuando decías no te corras castillo?? Ahora o te corras beta..,
888335,24999,2674640249436080,"Perros calientes, aquí en chile valen 1000 pesos y me e llegado a comer 4 jajajjajajajaj","vale,"
1132456,43325,1636097033545961,Jajaja por que son asi 😄,
1544755,6442,900999303984821,"Sofía, diste mucho en el deporte, eres campeona ,no tienes porqué estar rogando a nadie tu participación ,tu ya se entiende de antemano una de las primeras en estar en todo campeonato a realizarse ,no entiendo cómo existen peruanos en contra de otro peruano ,ya quisieran otros países tener a So...",
1897332,12707,580243363258960,Siii los etiquetan mucho,
800841,22468,1113094676326054,Hablen del protagonista de hoy SC,
747536,3230,211757217488721,Paula manzanal y yosmery son las mejores,
1313812,122687,396069431183876,Se corta la transmisión por segundos,
1027202,8913,729373618400470,¿Pero a qué hemos llegado para hablar de esto? 😅,"habla,"
1471391,20978,782397985447762,muy buenas informaciones acerca de los productos..,
1020115,40056,613643633303283,"Que ha pasao, contexto otra vez",
536467,38154,1011856393501046,El mejor de todos los tiempos. No ha llegado quien lo supere. 🥇🏆,

In [38]:
#https://towardsdatascience.com/emojis-aid-social-media-sentiment-analysis-stop-cleaning-them-out-bb32a1e5fc8e

In [39]:
#https://queirozf.com/entries/pandas-for-large-data